### ISSUE TITLE
Find data resource

### ISSUE THREAD

**Issue by WuLoMIn** [shijun18/mmTumorSeg#1]
Hello, I am a student from Hainan University.I want to replicate your code and learn from it.But I couldn't find a download of the corresponding data set online.Can you share them?

**Comment by shijun18** [comment]
Hello, I can provide the pre-processed data; the download link is https://rec.ustc.edu.cn/share/12b3a9c0-57a2-11ee-a29e-21e4bc551f06 password：2dfg. Please contact the organizing committee to get the original data, if necessary.

**Comment by WuLoMIn** [comment]
Thank you very much. And I wish you all the best.



---Original---
From: "Jun ***@***.***&gt;
Date: Wed, Sep 20, 2023 18:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shijun18/H-DenseFormer] Find data resource (Issue #1)




 
Hello, I can provide the pre-processed data; the download link is https://rec.ustc.edu.cn/share/12b3a9c0-57a2-11ee-a29e-21e4bc551f06 password：2dfg. Please contact the organizing committee to get the original data, if necessary.

**Comment by switch626** [comment]
Hey. Great jobs. But it shows "2023-12-31之前可访问,访问时间已过期！", Could you update this link if you are convenient?

**Comment by shijun18** [comment]
I have extended the sharing time of the download link. Enjoy it!

**Comment by switch626** [comment]
Got it! Thanks a lot!
